export const READ_BI = 'READ_BI';
export const IS_REGISTERED_SUCCESS = 'IS_REGISTERED_SUCCES';
export const RESET_REGISTER = 'RESET_REGISTER';
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const LOGIN = 'LOGIN';