export const IS_REGISTERED_SUCCESS = 'IS_REGISTERED_SUCCESS';
export const RESET_REGISTER = 'RESET_REGISTER';
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const LOGIN = 'LOGIN';

//Business Idea CRUD types
export const GET_ALL_BIS = 'GET_ALL_BIS';
export const GET_BI = 'GET_BI';
export const GET_BI_BY_OWNER = 'GET_BI_BY_OWNER';

export const UPDATING_DATA = 'UPDATING_DATA';
export const UPDATE_BI = 'UPDATE_BI';
export const UPDATE_BI_SUCCESS = 'UPDATE_BI_SUCCESS';

export const DELETING_DATA = 'DELETING_DATA';
export const DELETE_BI = 'DELETE_BI';
export const DELETE_BI_SUCCESS = 'DELETE_BI_SUCCESS';

//Profile CRUD Types
export const FETCHING_USER = 'FETCHING_USER';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

//UI Types
export const RESET_UI_STATE = 'RESET_UI_STATE';
export const LOADING_DATA = 'LOADING_DATA';

//Authentication Types
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const FETCH_INVESTOR_EMAIL = 'FETCH_INVESTOR_EMAIL';
export const FETCH_INVESTOR_EMAIL_LOADING = 'FETCH_INVESTOR_EMAIL_LOADING';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const REGISTER_BI_LOADING = 'REGISTER_BI_LOADING';
export const ADMIN_VERIFY = 'ADMIN_VERIFY';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const POST_EMAIL_RESET_LOADING = 'POST_EMAIL_RESET_LOADING';
export const POST_EMAIL_RESET_SUCCESS = 'POST_EMAIL_RESET_SUCCESS';
export const POST_EMAIL_RESET_FAIL = 'POST_EMAIL_RESET_FAIL';

export const GET_PROFILE_RECEIVER = 'GET_PROFILE_RECEIVER';
export const GET_PROFILE_SENDER = 'GET_PROFILE_SENDER';
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';


